### ISSUE TITLE
Explicit escaping vs HTML

### ISSUE THREAD

**Issue by grassator** [WebReflection/viperHTML#2]
I'm considering to use viperHTML in one of my projects, however I'm a really worried about the heuristic about which content is treated as HTML and which isn't, since it is very easy to accidentally create an XSS vulnerability.

Is there a way to make that choice explicit and always treat content as escaped text, unless marked otherwise? I would imagine something like this:

```js
render`
  <a href="${a.href}" onclick="${a.onclick}">
    ${a.text}
    <span>${raw(a.html)}</span>
  </a>
`;
```

**Comment by WebReflection** [comment]
It's very easy to distinguish, put a space or a new line around and that's text.

There are literally 3 rules to remember, that's KISS that won't change

**Comment by grassator** [comment]
@WebReflection Thank you for a fast answer and a clear indication that this is not a behavior you plan to change.

**Comment by WebReflection** [comment]
I can't because hyperHTML works the exact same and it makes no sense to change it. I've demoed simple to complex scenarios and your concern is not a real-world one. Mustache uses {{{ instead of {{ as example and you could argue same issue there. Having a global scope polluted with a raw method is something *you* can do at any time without changing anything in viperHTML.

Again, there are only 3 rules, your request would add more complexity and a global pollution for no real benefits. You need sanitized text? Don't put that part between >< ...that's it.
