### ISSUE TITLE
(Feature parity) Ignore null/undefined value for attributes

### ISSUE THREAD

**Issue by saschanaz** [WebReflection/viperHTML#35]
```js
require("viperhtml")`<tag attr=${null} />`.toString()
```

hyperHTML removes `attr` while viperHTML emits `attr="null"`.

**Comment by WebReflection** [comment]
the current optimizations over prefixed strings doesn't allow me to easily do that, so that passing `null || ''` might be a better work around.

I have written in the README the current status of this library:
https://github.com/WebReflection/viperHTML#warning

It's been a great first of a kind, but it would take a lot of effort to fully align it with _hyperHTML_ at this point, which is way more successful and used than this project.

Apologies if this was not the kind of answer you were expecting, but I am also sure you moved somewhere else since June 2019.

Closing as won't fix, thanks for your understanding.
