### ISSUE TITLE
Slash gets special meaning outside of interpolation

### ISSUE THREAD

**Issue by fernandocanizo** [WebReflection/viperHTML#38]
I didn't expect that characters outside of variable interpolation get a special meaning, however it seems viperhtml is doing something special with slashes (`/`).

Trimmed example:

```
const view = model => render`
<a href="/${model.loginOrLogout}">${model.loginOrLogout}</a>
`.toString();

const home = (req, res) => {
  const loginOrLogout = 'login'; // an `if` to decide for "logout" will be put later
  const model = {
    loginOrLogout,
  };
  res.send(view(model));
};
```

Notice the starting slash in the `href`, when I have that there, I get the following error:
```
TypeError: updates[(i - 1)] is not a function
```

If I took it out, page gets properly rendered.

**Comment by WebReflection** [comment]
`viperHTML` still follows the "_no partial attributes_" rule, so that you are not allowed to have sparse interpolations within attributes, hence you need to do instead:

```js
const view = model => render`
<a href="${'/' + model.loginOrLogout}">${model.loginOrLogout}</a>
`.toString();
```

I'll keep this open, but I don't have an eta to bring partial attributes in, a problem solved in [heresy-ssr](https://github.com/WebReflection/heresy-ssr#readme), which uses a different engine, and I suggest, for SSR, to give it a try.

**Comment by WebReflection** [comment]
P.S. please note that non-spares attributes have a performance boost too, compared to sparse attributes, so I hope you can deal with it for the time being, and enjoy the perf benefit out of the box.

**Comment by WebReflection** [comment]
For reference: https://github.com/WebReflection/viperHTML/issues/32

**Comment by WebReflection** [comment]
Actually, since duplicated of that one, I'll close this, and follow up there (at some point).
